package constants

const (
	// StorySubmitted ...
	StorySubmitted = "submitted"
	// StoryApproved ...
	StoryApproved = "approved"
	// StoryDenied ...
	StoryDenied = "denied"

	// DefaultStoryLimit ...
	DefaultStoryLimit int64 = 3
)
